name: Android CI # The name of the workflow

on: # The trigger for the workflow
  push: # The workflow runs when a new commit is pushed to the main branch
    branches: [ main ]
  pull_request: # The workflow also runs when a pull request is opened or updated
    branches: [ main ]

jobs: # The list of jobs for the workflow
  build: # The name of the first job

    runs-on: ubuntu-latest # The type of runner to use for the job

    steps: # The list of steps for the job
      - uses: actions/checkout@v3 # A predefined action that checks out the repository
      - name: set up JDK 11 # A custom name for the step
        uses: actions/setup-java@v3 # A predefined action that sets up the Java environment
        with: # The inputs for the action
          java-version: '11' # The version of Java to use
          distribution: 'temurin' # The distribution of Java to use
          cache: gradle # The option to cache the Gradle dependencies
      - name: Grant execute permission for gradlew # A custom name for the step
        run: chmod +x gradlew # A shell command to run
      - name: Build with Gradle # A custom name for the step
        run: ./gradlew build # A shell command to run
      - name: Release APK # A custom name for the step
        uses: r0user/release-apk@main # A predefined action that releases the APK
        with: # The inputs for the action
          releaseTitle: 'My App' # The title of the release
          appFolder: 'app' # The folder where the app is located
        env: # The environment variables for the action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GitHub token to authenticate the action
